"""Adding Video Game and Drawing categories

Revision ID: 63be6fc0db78
Revises: c2f7b61d9e13
Create Date: 2026-05-02 22:38:44.100192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63be6fc0db78'
down_revision: Union[str, Sequence[str], None] = 'c2f7b61d9e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
